name: Auto Version Bump

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'package.json'  # Don't run if package.json was just changed

jobs:
  check-and-bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Bump version
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          node scripts/version-bump.js
          
      - name: Check if there are changes
        id: changes
        run: |
          if git diff --quiet package.json; then
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push if version changed
        if: steps.changes.outputs.changes == 'true'
        run: |
          git add package.json
          git commit -m "Auto-bump version [skip ci]"
          git push 